from . import odoo_edi_primecargo_masterdata
from . import product_primecargo_wms_masterdata
from . import product_primecargo_shipping
from . import product_template
from . import product_product
from . import res_company
from . import res_config_settings
from . import res_country
from . import primecargo_agreement
from . import stock_picking
from . import res_country
from . import odoo_edi_primecargo_stock_picking_incoming
from . import odoo_edi_primecargo_stock_picking_outgoing
from . import odoo_edi_primecargo_stock_correction