from . import flexedi_document_format
from . import res_company
from . import flexedi_document_wms_picking
from . import product_primecargo_shipping
from . import res_country
from . import product_product
from . import product_template
from . import stock_picking
from . import res_config_settings